name = "dol-multiplayer"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "default-secret-change-in-production-50793fc84ea780240c9a602aa9c692b08952a02809486dfb32d83c181177dc3a"
APP_ENV = "production"

[deploy]
workers_dev = true